# appveyor.yml
# Configuration for continuous integration (CI).
# http://www.appveyor.com/about
# http://www.appveyor.com/docs/appveyor-yml

# Remote Desktop access to the build worker seems
# to require a paid AppVeyor account, rather than
# a free open-source account.
# http://www.appveyor.com/docs/how-to/rdp-to-build-worker

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
    COVERALLS_SERVICE_NAME: AppVeyor
    COVERALLS_REPO_TOKEN:
      secure: 3Zzoh/CPhOHYNZXKBEgi5nNOYrJ9wigKmomkk/VBB4A/KfEJlKUbGoMftMcJfARM

  matrix:

    # Python 2.7.10 is the latest version and is not pre-installed.

    - PYTHON: "C:\\Python27.10"
      PYTHON_VERSION: "2.7.10"
      PYTHON_ARCH: "32"

install:
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "pip install --disable-pip-version-check --user --upgrade pip"

  # Install InnoSetup for building a distributable setup wizard.
  - choco install -y InnoSetup

  # Install the build dependencies of the project. If some dependencies contain
  # compiled extensions and are not provided as pre-built wheel packages,
  # pip will build them from source using the MSVC compiler matching the
  # target Python version and architecture
  - "%CMD_IN_ENV% pip install -r requirements.txt"

  - "%CMD_IN_ENV% pip install pypiwin32"

  - "%CMD_IN_ENV% pip install coveralls"

  - "%CMD_IN_ENV% pip install --pre -f https://wxpython.org/Phoenix/snapshot-builds/ wxPython_Phoenix==3.0.3.dev2755+968784d"

  - "git submodule update --init --recursive"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "%CMD_IN_ENV% pip install pylint"
  - "pylint --rcfile=.pylintrc mydata"

  - "SET MYDATA_DEBUG_LOG_PATH=."
  - "python setup.py nosetests"

  - "SET CI_NAME=AppVeyor"
  - "SET CI_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%"
  - "SET CI_BUILD_URL=https://ci.appveyor.com/project/wettenhj/mydata/%APPVEYOR_BUILD_VERSION%"
  - "SET CI_BRANCH=%APPVEYOR_REPO_BRANCH%"
  - "coveralls"

after_test:
  # If tests are successful, create binary packages for the project.
  - "python setup.py bdist unsigned"
  - ps: "ls dist"

artifacts:
  # These can be downloaded after the build is complete:
  - path: .MyData_debug_log.txt
  - path: dist\*.exe
